# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  refugiados:
    container_name: refugiados
    image: refugiados
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile